/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeightRouteImport } from './routes/weight'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FoodsRouteImport } from './routes/foods'
import { Route as IndexRouteImport } from './routes/index'

const WeightRoute = WeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsRoute = FoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foods': typeof FoodsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weight': typeof WeightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foods': typeof FoodsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weight': typeof WeightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foods': typeof FoodsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/review': typeof ReviewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weight': typeof WeightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/foods'
    | '/profile'
    | '/reports'
    | '/review'
    | '/sitemap.xml'
    | '/weight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/foods'
    | '/profile'
    | '/reports'
    | '/review'
    | '/sitemap.xml'
    | '/weight'
  id:
    | '__root__'
    | '/'
    | '/foods'
    | '/profile'
    | '/reports'
    | '/review'
    | '/sitemap.xml'
    | '/weight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodsRoute: typeof FoodsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ReviewRoute: typeof ReviewRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeightRoute: typeof WeightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weight': {
      id: '/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof WeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods': {
      id: '/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof FoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodsRoute: FoodsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ReviewRoute: ReviewRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeightRoute: WeightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
